name: Issue Purifier

on:
  issues:
    types: [opened, reopened]

jobs:
  purify:
    runs-on: ubuntu-latest

    steps:
    
      - name: Match Template
        id: match-tpl
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actions: 'check-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body-includes: '请保留头部'
          
      - name: Check Switch
        id: check-switch
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actions: 'check-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body-includes: '- [ ] [R]/- [x] [U]'
      
      - name: Close If Malformed
        uses: actions-cool/issues-helper@v2.2.1
        if: steps.match-tpl.outputs.check-result != 'true' || steps.check-switch.outputs.check-result == 'true'
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}