name: Issue Purifier

on:
  issues:
    types: [opened, reopened]

jobs:
  purify:
    runs-on: ubuntu-latest

    steps:
      - name: Close If Malformed
        uses: actions-cool/issues-helper@v2.2.1
        if: contains(github.event.issue.body, '请保留头部') == 'false' || contains(github.event.issue.body, '- [] [R]') == 'true' || contains(github.event.issue.body, '- [] [U]') == 'false'
        with:
          actions: 'close-issue'
          issue-number: ${{ github.event.issue.number }}